apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
spec:
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      containers:
        - name: backend-a
          image: 057196872298.dkr.ecr.us-east-2.amazonaws.com/a-service:latest
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 8080