apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
spec:
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      containers:
        - name: backend-a
          image: 057196872298.dkr.ecr.us-west-2.amazonaws.com/service-a
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080